name: RELEASE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: 🚀 Build App
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --global --production windows-build-tools
      - run: npm i --legacy-peer-deps
      - run: npm run electron:build

      - name: CREATE RELEASE
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*.exe"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
